# Generated by Django 5.0.6 on 2024-07-02 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Название')),
                ('product_price', models.IntegerField(default=0, verbose_name='Цена')),
                ('product_images', models.ImageField(null=True, upload_to='kebab/images/', verbose_name='Иллюстрация')),
                ('is_active', models.BooleanField(choices=[(False, 'Склад'), (True, 'Продажа')], default=0, verbose_name='Статус')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kebab.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Позиция меню',
                'verbose_name_plural': 'Позиции меню',
                'ordering': ['categories', 'product_price'],
            },
        ),
    ]
