# Generated by Django 5.0.6 on 2024-06-17 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField(default=0)),
                ('product_images', models.ImageField(null=True, upload_to='images')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kebab.category')),
            ],
            options={
                'ordering': ['categories'],
            },
        ),
    ]
