# Generated by Django 5.0.6 on 2024-06-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kebab', '0002_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['categories', 'product_price']},
        ),
    ]
