# Generated by Django 5.0.6 on 2024-06-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebab', '0006_alter_products_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
