# Generated by Django 5.0.6 on 2024-06-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kebab', '0007_alter_products_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(choices=[(False, 'Склад'), (True, 'Продажа')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_images',
            field=models.ImageField(null=True, upload_to='kebab/images/'),
        ),
    ]
